// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenerateResult = { puzzle: string, solution: string, difficulty: string, seed: number };
