// Type declarations for @repo/sudoku-wasm.
// Data types are generated by `cargo test` (ts-rs) into bindings/.
// WASM function signatures are maintained here alongside the Rust API.

export type { GenerateResult } from './bindings/GenerateResult';
export type { HintResult } from './bindings/HintResult';
export type { ValidateResult } from './bindings/ValidateResult';

export function generate(difficulty?: string, seed?: number): import('./bindings/GenerateResult').GenerateResult;
export function solve(board: string): string | null;
export function validate(board: string): import('./bindings/ValidateResult').ValidateResult;
export function hint(board: string): import('./bindings/HintResult').HintResult | undefined;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
  readonly memory: WebAssembly.Memory;
}

export default function init(input?: { module_or_path?: InitInput } | InitInput): Promise<InitOutput>;
